language: ruby
rvm:
  - 2.1.2
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake test
before_script:
  - cp config/database.yml.sample config/database.yml
